name: Pipeline

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  run-unit-and-integration-tests:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/development' || github.ref == 'refs/heads/release'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew test --tests '*.*Unit*'

      - name: Run integration tests
        run: ./gradlew test --tests '*.*Integration*'

  deploy-to-staging-and-run-further-tests:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release' || (github.event_name == 'pull_request' && github.base_ref == 'release' && github.head_ref == 'main')
    needs: run-unit-and-integration-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List contents of the system directory
        run: ls -la src/test/system/MainQuest.postman_collection.json
        working-directory: ${{github.workspace}}

      - name: Run system tests
        run: |
          npm install -g newman
          newman run src/test/system/*


      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Get project version
        run: echo "PROJECT_VERSION=$(./gradlew -q printVersion)" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/spring
          tag: ${{ env.PROJECT_VERSION }}
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Checkout GitOps repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.actor }}/ArgoCD_GitOps
          token: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}
          ref: main

      - name: Update image tag in values.yml
        run: |
          sed -i "s/tag: .*/tag: ${{ env.PROJECT_VERSION }}/" values_staging.yml

      - name: Commit and push changes to GitOps repository
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git add values_staging.yml
          git commit --allow-empty -m "Deploy ${{ env.PROJECT_VERSION }} to staging"
          git push

      - name: Wait for ArgoCD deployment
        run: |
          # Add commands to check the status of ArgoCD deployment here
          # You may use ArgoCD CLI or API to check the deployment status
          # Example:
          # argocd app wait <APP_NAME> --timeout 300

      - name: Checkout Git SpringBoot Repository for SystemTest
        uses: action/checkout@v4
        with:
          repository: ${{ github.actor }}/SpringBoot_ArgoCD
          token: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}
          ref: main

      - name: List contents of the system directory
        run: ls -la src/test/system/MainQuest.postman_collection.json
        working-directory: ${{github.workspace}}

      - name: Run system tests
        run: |
          npm install -g newman
          newman run src/test/system/*



  deploy-to-production:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout GitOps repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.actor }}/ArgoCD_GitOps
          token: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}
          ref: main

      - name: Create a new branch for production deployment
        run: |
          git checkout -b deploy/${{ env.PROJECT_VERSION }}

      - name: Update image tag with version from staging in production values.yml
        run: |
          version=$(grep 'tag:' values_staging.yml | awk '{print $2}')
          sed -i "s/tag: .*/tag: $version/" values_production.yml

      - name: Commit changes to new branch
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git add values_production.yml
          git commit -m "Update production image tag to $version"
          git push --set-upstream origin deploy/${{ env.PROJECT_VERSION }}

      - name: Create a pull request from the new branch to main
        run: |
          gh pr create --title "Deploying version ${{ env.PROJECT_VERSION }}" --body "This PR updates the production image tag to $version." --base main --head deploy/${{ env.PROJECT_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}
